"use client";

import Link from "next/link";
import { useState } from "react";

import { Button } from "@/components/Button";
import {
  generatedDocumentDownloadFilename,
  generatedDocumentToMarkdown,
} from "@/lib/generation/export";
import type { GeneratedDocumentRow } from "@/types/generation";

type GeneratedDocumentWorkspaceProps = {
  document: GeneratedDocumentRow;
};

export function GeneratedDocumentWorkspace({
  document: doc,
}: GeneratedDocumentWorkspaceProps) {
  const [copied, setCopied] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const content = doc.generated_content;
  const markdownText = generatedDocumentToMarkdown(content, doc.created_at);
  const filename = generatedDocumentDownloadFilename(content.title);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdownText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error("Failed to copy to clipboard:", err);
    }
  };

  const handleDownload = () => {
    setIsDownloading(true);
    try {
      const blob = new Blob([markdownText], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to trigger download:", err);
    } finally {
      setIsDownloading(false);
    }
  };

  const sortedSections = [...(content.sections ?? [])].sort(
    (a, b) => a.order - b.order,
  );

  const formattedDate = new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(doc.created_at));

  return (
    <div className="space-y-8">
      {/* Header Banner */}
      <div className="rounded-xl border border-border bg-surface p-6 space-y-4">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex items-center gap-2">
              <span className="rounded-full bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-0.5 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
                ✓ Draft Saved
              </span>
              <span className="text-xs text-muted font-mono">{formattedDate}</span>
            </div>
            <h1 className="mt-2 text-2xl font-bold tracking-tight text-foreground">
              {content.title}
            </h1>
            <p className="mt-1 text-xs text-muted">
              Document Type:{" "}
              <span className="font-semibold text-foreground">
                Freelance Service Agreement
              </span>
              {doc.model ? (
                <span className="ml-2 font-mono text-muted">
                  (Generated by {doc.model})
                </span>
              ) : null}
            </p>
          </div>

          <div className="flex flex-wrap gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={handleCopy}
              className="text-xs"
            >
              {copied ? "✓ Copied to Clipboard" : "Copy Markdown"}
            </Button>

            <Button
              type="button"
              onClick={handleDownload}
              disabled={isDownloading}
              className="text-xs"
            >
              {isDownloading ? "Preparing..." : "Download Markdown (.md)"}
            </Button>
          </div>
        </div>

        {/* Parties summary card */}
        <div className="rounded-lg border border-border/80 bg-background/50 p-4 text-xs space-y-2">
          <p className="font-semibold text-foreground uppercase tracking-wider text-[10px]">
            Agreed Parties
          </p>
          <div className="grid gap-2 sm:grid-cols-2">
            <div>
              <span className="text-muted">Freelancer:</span>{" "}
              <span className="font-medium text-foreground">
                {content.parties.freelancerName}
              </span>
            </div>
            <div>
              <span className="text-muted">Client:</span>{" "}
              <span className="font-medium text-foreground">
                {content.parties.clientName}
              </span>
            </div>
          </div>
          {content.parties.clientAddress ? (
            <div>
              <span className="text-muted">Client Address:</span>{" "}
              <span className="text-foreground font-mono">
                {content.parties.clientAddress}
              </span>
            </div>
          ) : null}
        </div>
      </div>

      {/* Navigation Actions bar */}
      <div className="flex items-center justify-between text-xs">
        <Link
          href="/dashboard/create"
          className="text-accent hover:underline font-medium flex items-center gap-1"
        >
          ← Create another agreement
        </Link>
        <Link
          href="/dashboard"
          className="text-muted hover:text-foreground font-medium"
        >
          Return to Dashboard →
        </Link>
      </div>

      {/* Structured Sections Document View */}
      <div className="space-y-6">
        <div className="flex items-center justify-between border-b border-border/60 pb-3">
          <h2 className="text-base font-bold text-foreground">
            Agreement Sections ({sortedSections.length})
          </h2>
          <span className="text-xs text-muted">
            Section IDs preserved for future explanation & review
          </span>
        </div>

        {sortedSections.map((sec) => (
          <article
            key={sec.id}
            id={`section-${sec.id}`}
            className="rounded-xl border border-border bg-surface p-6 space-y-3 transition-colors hover:border-accent/30"
          >
            <div className="flex items-center justify-between">
              <h3 className="text-base font-bold text-foreground">
                {sec.order + 1}. {sec.title}
              </h3>
              <span className="rounded bg-accent/10 border border-accent/20 px-2 py-0.5 text-[10px] font-mono text-accent">
                id: {sec.id}
              </span>
            </div>

            <div className="prose prose-sm dark:prose-invert max-w-none text-sm text-foreground/90 whitespace-pre-line leading-relaxed">
              {sec.content}
            </div>
          </article>
        ))}
      </div>

      {/* Legal Disclaimer Card */}
      <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-5 text-xs text-amber-800 dark:text-amber-300 space-y-2">
        <div className="flex items-center gap-2 font-bold">
          <span>⚠️ Important Legal Notice</span>
        </div>
        <p className="leading-normal">{content.disclaimer}</p>
      </div>
    </div>
  );
}
